name: Test Simple Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test basic commands
      run: |
        echo "Testing basic functionality..."
        pwd
        ls -la
        echo "Ubuntu version:"
        cat /etc/os-release
        echo "Git version:"
        git --version
        echo "Make version:"
        make --version
        echo "Test completed successfully!"
